### ISSUE TITLE
More Buttons

### ISSUE THREAD

**Issue by RobertGreen-25** [VertisanPRO/tracker#37] opened 2024-02-04 19:28 UTC
### Product

Quantum

### Describe the solution you'd like

Add a feature that allows us to create custom buttons on the console

### Additional context

![image](https://github.com/VertisanPRO/tracker/assets/142682946/24ebe3d8-284a-4736-9e34-8c7b7fcd63c7)
![image](https://github.com/VertisanPRO/tracker/assets/142682946/7e8035d0-ff88-42b8-b41f-36027d402e88)

**Comment by PadowYT2** [comment] 2024-02-20 12:38
Where would this be at with the new design?

![https://cdn.padow.ru/gt7Qa](https://cdn.padow.ru/gt7Qa)

**Comment by RobertGreen-25** [comment] 2024-02-20 17:59
> Where would this be at with the new design?
> 
> ![https://cdn.padow.ru/gt7Qa](https://camo.githubusercontent.com/d938e2e6784323946a24b0f9450573bdccc677ac2f39fd7a4d1e317ab93a4298/68747470733a2f2f63646e2e7061646f772e72752f6774375161)

Yes, That would be nice to have the buttons next to that start | Restart | Stop | kill buttons

**Comment by PadowYT2** [comment] 2024-02-20 18:00
> > Where would this be at with the new design?
> > ![https://cdn.padow.ru/gt7Qa](https://camo.githubusercontent.com/d938e2e6784323946a24b0f9450573bdccc677ac2f39fd7a4d1e317ab93a4298/68747470733a2f2f63646e2e7061646f772e72752f6774375161)
> 
> Yes, That would be nice to have the buttons next to that start | Restart | Stop | kill buttons

If I put the button next to them, the title won't have enough space, and on mobile it will look really bad cramped up

**Comment by RobertGreen-25** [comment] 2024-02-20 18:13
> > > Where would this be at with the new design?
> > > ![https://cdn.padow.ru/gt7Qa](https://camo.githubusercontent.com/d938e2e6784323946a24b0f9450573bdccc677ac2f39fd7a4d1e317ab93a4298/68747470733a2f2f63646e2e7061646f772e72752f6774375161)
> > 
> > 
> > Yes, That would be nice to have the buttons next to that start | Restart | Stop | kill buttons
> 
> If I put the button next to them, the title won't have enough space, and on mobile it will look really bad cramped up

Or maybe under files or sub users

**Comment by PadowYT2** [comment] 2024-02-20 18:15
If you would like that, this issue will be closed as this is a duplicate of #27

**Closed** 2024-02-20 19:56 UTC
Labels: duplicate, enhancement, invalid, quantum
